source 'https://rubygems.org'
gem 'rails', '~> 3.2.16'
gem 'sqlite3'
gem 'devise'
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end
gem 'jquery-rails'
gem 'bootstrap-sass', '>= 3.0.0.0'
gem 'thin'
group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'hub', :require=>nil
  gem 'quiet_assets'
  gem 'rails_layout'
end
group :test do
  gem 'minitest-spec-rails'
  gem 'minitest-wscolor'
end
